services:

  mlflow:
    image: python:3.9-slim
    container_name: fraudguard-mlflow

    working_dir: /mlflow

    volumes:
      - ./mlruns:/mlflow/mlruns

    ports:
      - "5001:5000"

    command: >
      sh -c "
      pip install mlflow==2.22.5 &&
      mlflow server
      --backend-store-uri file:///mlflow/mlruns
      --default-artifact-root file:///mlflow/mlruns
      --host 0.0.0.0
      --port 5000
      "


  api:
    build: .
    container_name: fraudguard-api

    ports:
      - "8000:8000"

    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000

    depends_on:
      - mlflow